# Generated by Django 4.0.1 on 2022-03-29 11:46

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание категории')),
                ('color', colorfield.fields.ColorField(default='#006CFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Времени добавлено')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата активности')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timerecord.category')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название цели')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='Описание цели')),
                ('target_hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Часов необходимо')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Значимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_achieved', models.BooleanField(default=False, verbose_name='Achieved?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/', verbose_name='Изображение цели')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timerecord.goal'),
        ),
    ]
