# Generated by Django 4.0.1 on 2022-02-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timerecord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='comment',
            new_name='description',
        ),
    ]
