# Generated by Django 4.0.1 on 2022-02-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerecord', '0002_rename_comment_goal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение цели'),
        ),
    ]
