# Generated by Django 4.0.1 on 2022-02-19 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerecord', '0003_alter_goal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(verbose_name='Описание цели'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_achieved',
            field=models.BooleanField(default=False, verbose_name='Достигнута'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Значимость'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_hours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Часов необходимо'),
        ),
    ]
