# Generated by Django 4.0.1 on 2022-02-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerecord', '0004_alter_goal_description_alter_goal_is_achieved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='slug',
            field=models.SlugField(),
        ),
    ]
