# Generated by Django 4.0.1 on 2022-02-23 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timerecord', '0005_alter_goal_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание категории')),
                ('color', models.CharField(choices=[('Blue', '66, 135, 245'), ('Red', '181, 0, 36'), ('Green', '0, 143, 12'), ('Orange', '194, 101, 2')], default='Red', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='timerecord.goal')),
            ],
        ),
    ]
