# Generated by Django 4.0.1 on 2022-02-23 06:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timerecord', '0006_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timerecord.goal'),
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Времени добавлено')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата активности')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timerecord.category')),
            ],
        ),
    ]
