# Generated by Django 4.0.1 on 2022-02-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerecord', '0007_alter_category_goal_timerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
