# Generated by Django 4.0.1 on 2022-02-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerecord', '0008_alter_goal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображение цели'),
        ),
    ]
