# Generated by Django 4.0.1 on 2022-03-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerecord', '0009_alter_goal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='is_achieved',
            field=models.BooleanField(default=False, verbose_name='Achieved?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название цели'),
        ),
    ]
