# Generated by Django 4.0.1 on 2022-03-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerecord', '0010_alter_goal_is_achieved_alter_goal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображение цели'),
        ),
    ]
