# Generated by Django 4.0.1 on 2022-03-13 05:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timerecord', '0012_goal_user_alter_goal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.AddField(
            model_name='category',
            name='hex_color',
            field=colorfield.fields.ColorField(default='#006CFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
