version: '3'

volumes:
  postgres_data:

services:
  db:
    container_name: postgre-database
    image: postgres:13.0-alpine
    volumes:
      - $HOME/python/data/gladwelldata:/var/lib/postgresql/data/
      - ./sql/:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
