"""Initial Migration

Revision ID: 2f84eb6cf289
Revises: 5a01a79b44bf
Create Date: 2023-01-07 19:36:53.543664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f84eb6cf289'
down_revision = '5a01a79b44bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
