"""Add Tutorial model

Revision ID: 936cb4f0a15d
Revises:
Create Date: 2022-11-30 22:40:33.324775

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "936cb4f0a15d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutorials",
        sa.Column("tutorial_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("tutorial_id"),
    )
    op.drop_table("goals")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goals",
        sa.Column("goal_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "description1", sa.VARCHAR(length=250), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "expired_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("duration", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("goal_id", name="goals_pkey"),
    )
    op.drop_table("tutorials")
    # ### end Alembic commands ###
