"""Fix naming mistake in goals

Revision ID: 98a6b54f6e99
Revises: 15862d06a140
Create Date: 2022-12-03 15:33:12.432639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a6b54f6e99'
down_revision = '15862d06a140'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('description', sa.String(length=250), nullable=True))
    op.drop_column('goals', 'description1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('description1', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('goals', 'description')
    # ### end Alembic commands ###
