# Generated by Django 4.0.1 on 2022-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_achiever_delete_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='achiever',
            name='last_name',
            field=models.CharField(default='Kleschov', max_length=50),
            preserve_default=False,
        ),
    ]
